- hosts: kubernetes
  tasks:
    - name: stop ntpd
      service:
        name=ntpd
        enabled=yes
        state=stopped

    - name: start ntpd
      service:
        name=ntpd
        enabled=yes
        state=started

    - name: Is NTP started
      service:
        name=ntpd
        enabled=yes
        state=status
